[package]
name = "keys"
description = "Keyboard layer manager."
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = [ "derive", "cargo" ] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = [ "full" ] }
